services:
  - type: web
    name: diva-central-asia-2025
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
      - key: WEBHOOK_DOMAIN
        value: "https://diva-central-asia-2025.onrender.com"
